# Example configuration for Milvus with external Kafka using secret credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: milvus-kafka-credentials
  namespace: milvus-system
type: Opaque
data:
  # Base64 encoded username and password
  username: bWlsdnVzLXVzZXI=  # milvus-user
  password: bWlsdnVzLXBhc3M=  # milvus-pass
---
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  namespace: milvus-system
  labels:
    app: milvus
spec:
  mode: cluster
  config:
    kafka:
      # Security configuration for Kafka
      securityProtocol: SASL_PLAINTEXT
      saslMechanisms: PLAIN
      # Note: saslUsername and saslPassword will be automatically injected
      # from the secret specified in dependencies.kafka.secretRef
  dependencies:
    msgStreamType: kafka
    kafka:
      external: true
      # Reference to the secret containing Kafka credentials
      secretRef: "milvus-kafka-credentials"
      brokerList:
        - "kafka-broker-1:9092"
        - "kafka-broker-2:9092"
        - "kafka-broker-3:9092"
    storage:
      type: MinIO
      endpoint: "minio:9000"
      secretRef: "milvus-storage-credentials"
    etcd:
      endpoints:
        - "etcd:2379"
