# This is a sample to deploy a milvus cluster using mixCoord instead of rootCoord, indexCoord, dataCoord and queryCoord.

apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  dependencies: {}
  components: 
    # now mixCoord is used by default
    # mixCoord deploys all coordinators in one 'mixture' deployment
    mixCoord:
      replicas: 1
  config: {}