# This sample file is used to deploy Milvus with Azure Storage as its object storage with connection string.
# change the <parameters> to match your environment
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  components:
    env:
    - name: AZURE_CONNECTION_STRING
      value: <my-azure-connection-string>
  config:
    common:
      storageType: remote
    minio:
      cloudProvider: azure
      bucketName: <my-container-name>
      rootPath: milvus/my-release
      accessKeyID: <my-storage-account>
      useSSL: true
  dependencies:
    storage:
      external: true
      type: Azure
      endpoint: core.windows.net:443
