# This is a sample to add custom configurations for milvus
# It changes the etcd's rootPath, minio's bucketName and log's level
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  dependencies: {}
  components: {}
  # check full configuration options at https://github.com/milvus-io/milvus/blob/master/configs/milvus.yaml
  config:
    etcd:
      rootPath: my-release
    minio:
      bucketName: my-bucket
    log:
      level: debug