# This sample file is used to deploy Milvus with External Kafka Signed by Private CA - Read credentials via secrets.
# change the <parameters> to match your environment

---
apiVersion: v1
data:
  ca-cert: <ca.cert>
  client-cert: <client.cert>
  client-key: <client.key>
kind: Secret
metadata:
  name: kafka-ssl-secret
  namespace: milvus
type: Opaque
---
apiVersion: v1
data:
  sasl-password: <sasl-password>
  sasl-username: <sasl-user>
  tls-key-password: <tls-password>
kind: Secret
metadata:
  name: kafka-passwords
  namespace: milvus
type: Opaque
---
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: ""
  namespace: ""
  labels:
    app: milvus
spec:
  mode: cluster

  config:
    kafka:
      brokerList:
        - "<kafka_broker>:9094"
      securityProtocol: SASL_SSL
      saslMechanisms: SCRAM-SHA-512
      saslUsernameSecret:
        name: kafka-passwords
        key: sasl-username
        namespace: milvus
      saslPasswordSecret:
        name: kafka-passwords
        key: sasl-password
        namespace: milvus
      ssl:
        enabled: true
        caCertSecret:
          name: kafka-ssl-secret
          key: ca-cert
          namespace: milvus
        # optional client auth:
        # certSecret:
        #   name: kafka-ssl-secret
        #   key: client-cert
        #   namespace: milvus
        # keySecret:
        #   name: kafka-ssl-secret
        #   key: client-key
        #   namespace: milvus
        # keyPasswordSecret:
        #   name: kafka-passwords
        #   key: tls-key-password
        #   namespace: milvus
  dependencies:
    msgStreamType: kafka
    kafka:
      external: true
      brokerList:
        - "<kafka_broker>:9094"