{{- if .Values.installDependencies.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "chart.fullname" . }}-checker-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-checker-role'
subjects:
- kind: ServiceAccount
  name: {{ include "chart.checkerServiceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}
