apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels: {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels: {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      containers:
      - args:
        - -namespace
        - {{ .Release.Namespace | quote }}
        - -name
        - {{ include "chart.fullname" . | quote }}
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --leader-elect
        {{- if .Values.enableWebhook }}
        - --webhook=true
        {{- end }}
        command:
        - /manager
        image: '{{.Values.image.repository}}:{{.Values.image.tag|default .Chart.AppVersion}}'
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.allowPrivilegeEscalation }}
        {{- if .Values.enableWebhook }}
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- end }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "chart.serviceAccountName" . | quote }}
      terminationGracePeriodSeconds: 10
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- if .Values.enableWebhook }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "chart.fullname" . }}-webhook-cert
      {{- end }}
