apiVersion: batch/v1
kind: Job
metadata:
  annotations: {{- toYaml .Values.checker.annotations | nindent 4 }}
  labels: {{- include "chart.labels" . | nindent 4 }}
  name: "{{ .Release.Name }}-checker"
  namespace: {{ .Release.Namespace | quote }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "chart.checkerServiceAccountName" . | quote }}
      restartPolicy: OnFailure
      containers:
      - name: checker
        image: '{{.Values.image.repository}}:{{.Values.image.tag|default .Chart.AppVersion}}'
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["/checker"]
        args:
          - "-namespace={{ .Release.Namespace }}"
          - "-name={{ .Release.Name }}"
          {{- if .Values.checker.disableCertManagerCheck }}
          - "-disable-cert-manager-check"
          {{- end }}
          {{- if .Values.checker.disableCertManagerInstall }}
          - "-disable-cert-manager-install"
          {{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
