# This file contains recommended default values for a production deployment
persistence: true
extra: {}
monitoring: {}
volumes:
  persistence: true
  local_storage: false

components:
  # zookeeper
  zookeeper: true
  # bookkeeper
  bookkeeper: true
  # bookkeeper - autorecovery
  autorecovery: true
  # broker
  broker: true
  # functions
  functions: false
  # proxy
  proxy: true
  # toolset
  toolset: false
  # pulsar manager
  pulsar_manager: false

images:
  zookeeper:
    repository: apachepulsar/pulsar
    tag: 3.0.7
    pullPolicy: IfNotPresent
  bookie:
    repository: apachepulsar/pulsar
    tag: 3.0.7
    pullPolicy: IfNotPresent
  autorecovery:
    repository: apachepulsar/pulsar
    tag: 3.0.7
    pullPolicy: IfNotPresent
  broker:
    repository: apachepulsar/pulsar
    tag: 3.0.7
    pullPolicy: IfNotPresent
  proxy:
    repository: apachepulsar/pulsar
    tag: 3.0.7
    pullPolicy: IfNotPresent

zookeeper:
  pdb:
    usePolicy: false
  affinity:
    anti_affinity: false
  component: zookeeper
  replicaCount: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 0.2
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    data:
      name: data
      size: 20Gi
      local_storage: false
  configData:
    PULSAR_MEM: >
      -Xms256m -Xmx256m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -Dcom.sun.management.jmxremote
      -Djute.maxbuffer=10485760
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:+DisableExplicitGC
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem

bookkeeper:
  pdb:
    usePolicy: false
  affinity:
    anti_affinity: false
  component: bookie
  replicaCount: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 2048Mi
      cpu: 0.5
  volumes:
    # use a persistent volume or emptyDir
    persistence: true
    journal:
      name: journal
      size: 100Gi
      local_storage: false
    ledgers:
      name: ledgers
      size: 200Gi
      local_storage: false
  configData:
    PULSAR_MEM: >
      -Xms4096m
      -Xmx4096m
      -XX:MaxDirectMemorySize=8192m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
    nettyMaxFrameSizeBytes: "104867840"
autorecovery:
  affinity:
    anti_affinity: false
  component: recovery
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 0.1
  podMonitor:
    enabled: false
  configData:
    BOOKIE_MEM: >
      -Xms128m -Xmx128m
    PULSAR_PREFIX_useV2WireProtocol: "true"
pulsar_metadata:
  component: pulsar-init
  image:
    repository: apachepulsar/pulsar
    tag: 3.0.7
    pullPolicy: IfNotPresent

broker:
  pdb:
    usePolicy: false
  affinity:
    anti_affinity: false
  component: broker
  replicaCount: 2
  autoscaling:
    enabled: false
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 2048Mi
      cpu: 0.5
  configData:
    PULSAR_MEM: >
      -Xms4096m -Xmx4096m -XX:MaxDirectMemorySize=8192m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -Dio.netty.leakDetectionLevel=disabled
      -Dio.netty.recycler.linkCapacity=1024
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
    managedLedgerDefaultEnsembleSize: "3"
    managedLedgerDefaultWriteQuorum: "3"
    managedLedgerDefaultAckQuorum: "2"
    maxMessageSize: "104857600"
    defaultRetentionTimeInMinutes: "10080"
    defaultRetentionSizeInMB: "-1"
    backlogQuotaDefaultLimitGB: "8"
    ttlDurationDefaultInSeconds: "259200"
    subscriptionExpirationTimeMinutes: "3"
    backlogQuotaDefaultRetentionPolicy: producer_exception

proxy:
  pdb:
    usePolicy: false
  affinity:
    anti_affinity: false
  component: proxy
  replicaCount: 2
  autoscaling:
    enabled: false
  podMonitor:
    enabled: false
  resources:
    requests:
      memory: 1024Mi
      cpu: 0.5
  configData:
    PULSAR_MEM: >
      -Xms512m -Xmx512m -XX:MaxDirectMemorySize=2048m
    PULSAR_GC: >
      -XX:+UseG1GC
      -XX:MaxGCPauseMillis=10
      -Dio.netty.leakDetectionLevel=disabled
      -Dio.netty.recycler.linkCapacity=1024
      -XX:+ParallelRefProcEnabled
      -XX:+UnlockExperimentalVMOptions
      -XX:+DoEscapeAnalysis
      -XX:ParallelGCThreads=4
      -XX:ConcGCThreads=4
      -XX:G1NewSizePercent=50
      -XX:+DisableExplicitGC
      -XX:-ResizePLAB
      -XX:+ExitOnOutOfMemoryError
      -XX:+PerfDisableSharedMem
    httpNumThreads: "8"
  ports:
    http: 80
    https: 443
    pulsar: 6650
    pulsarssl: 6651
    containerPorts:
      http: 8080
      https: 8443
  service:
    annotations: {}
    type: ClusterIP

kube-prometheus-stack:
  crds:
    enabled: false
  enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false
