name: Chart Lint Test

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  chart-lint-test:
    name: Chart Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: v3.4.0
      - name: Add dependency chart repos
        run: |
          helm repo add cert-manager https://charts.jetstack.io

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --all --config ct.yaml

      - name: Create KinD cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

      - name: Run chart-testing (install)
        id: install
        run: ct install --all --config ct.yaml
