name: Chart Lint Test

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  chart-lint-test:
    name: Chart Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.4.0
      - name: Add dependency chart repos
        run: |
          helm repo add cert-manager https://charts.jetstack.io

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --all --config ct.yaml

      - name: Create KinD cluster
        uses: helm/kind-action@v1.2.0

      - name: Run chart-testing (install)
        id: install
        run: ct install --all --config ct.yaml
